# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.1"

gem "avro_turf"
gem "erubi", ">= 1.5"
gem "karafka", ">= 2.0.0.alpha2"
gem "puma"
gem "rack-unreloader", ">= 1.8"
gem "rake"
gem "refrigerator", ">= 1"
gem "roda", ">= 3.50"
gem "sassc", ">= 2"
gem "sequel", ">= 5"
gem "sequel_pg", ">= 1.8", require: "sequel"
gem "tilt", ">= 2.0.9"

group :development do
  gem "sequel-annotate"
end

group :test do
  gem "capybara"
  gem "minitest", ">= 5.7.0"
  gem "minitest-global_expectations"
  gem "minitest-hooks", ">= 1.1.0"
end
