# frozen_string_literal: true

class Payment < Sequel::Model
end

# Table: payments
# Columns:
#  id                    | bigint         | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  public_id             | uuid           | NOT NULL DEFAULT gen_random_uuid()
#  transaction_public_id | uuid           | NOT NULL
#  status                | payment_status | NOT NULL
# Indexes:
#  payments_pkey          | PRIMARY KEY btree (id)
#  payments_public_id_key | UNIQUE btree (public_id)
