# frozen_string_literal: true

class Task < Sequel::Model
  REWARD = -> { rand(20..40) }.freeze
  COST = -> { rand(10..20) }.freeze

  many_to_one :account, primary_key: :public_id, key: :assignee_public_id

  def self.add(public_id:, assignee_public_id:)
    DB.transaction do
      task = for_update.first(public_id:)
      if task.nil?
        task = create(public_id:, assignee_public_id:, cost: COST.call, reward: REWARD.call)
      else
        task.update(cost: COST.call, reward: REWARD.call)
      end
      tr = Transaction.create(
        account_public_id: assignee_public_id,
        type: "deposit",
        debit: task.cost
      )
      [task, tr]
    end
  end

  def self.close(public_id:)
    DB.transaction do
      task = for_update.first(public_id:)
      return "Implement retry in 10 minutes" if task.nil? || task.reward.nil?

      tr = Transaction.create(
        account_public_id: task.assignee_public_id,
        type: "withdraw",
        credit: task.reward
      )
      [task, tr]
    end
  end

  def self.change_assignee(public_id:, assignee_public_id:)
    DB.transaction do
      task = for_update.first(public_id:)
      return "Implement retry in 10 minutes" if task.nil?

      task.update(assignee_public_id:)
      tr = Transaction.create(
        account_public_id: assignee_public_id,
        type: "deposit",
        debit: task.cost
      )
      [task, tr]
    end
  end

  def self.create_or_update(attrs)
    DB.transaction do
      task = for_update.first(public_id: attrs["public_id"])
      task = create(public_id: attrs["public_id"]) if task.nil?
      task.update_fields(attrs, %w[assignee_public_id description jira_id])
    end
  end
end

# Table: tasks
# Columns:
#  id                 | integer | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  description        | text    | NOT NULL DEFAULT ''::text
#  assignee_public_id | uuid    |
#  public_id          | uuid    | NOT NULL DEFAULT gen_random_uuid()
#  cost               | integer |
#  reward             | integer |
#  jira_id            | text    | NOT NULL DEFAULT ''::text
# Indexes:
#  tasks_pkey          | PRIMARY KEY btree (id)
#  tasks_public_id_key | UNIQUE btree (public_id)
