# frozen_string_literal: true

class Task < Sequel::Model
  STATUSES = %w[open closed].freeze

  many_to_one :account, primary_key: :public_id, key: :assignee_public_id
end

# Table: tasks
# Columns:
#  id                 | integer       | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  description        | text          | NOT NULL DEFAULT ''::text
#  status             | task_status   | NOT NULL DEFAULT 'open'::task_status
#  assignee_public_id | uuid          | NOT NULL
#  public_id          | uuid          | NOT NULL DEFAULT gen_random_uuid()
#  cost               | numeric(10,2) | NOT NULL
#  jira_id            | text          | NOT NULL DEFAULT ''::text
# Indexes:
#  tasks_pkey          | PRIMARY KEY btree (id)
#  tasks_public_id_key | UNIQUE btree (public_id)
