# frozen_string_literal: true

class Transaction < Sequel::Model
  PROFIT = Sequel.lit(
    "coalesce(sum(amount) FILTER (WHERE account_type = 'debit'), 0) - "\
    "coalesce(sum(amount) FILTER (WHERE account_type = 'credit'), 0) AS dif"
  ).freeze
  UNPROFIT = Sequel.lit(
    "coalesce(sum(amount) FILTER (WHERE account_type = 'credit'), 0) - "\
    "coalesce(sum(amount) FILTER (WHERE account_type = 'debit'), 0) AS dif"
  ).freeze

  dataset_module do
    def today
      now = Time.now.utc
      beginning_of_day = Time.utc(now.year, now.month, now.day)
      where(performed_at: beginning_of_day..now)
    end
  end

  def self.top_management_profit(time_period_human)
    now = Time.now.utc
    time_period =
      case time_period_human
      when "today"
        beginning_of_day = Time.utc(now.year, now.month, now.day)
        beginning_of_day..now
      when "alltime"
        Time.at(0)..now
      else
        raise "Not implemented"
      end
    where(performed_at: time_period).select(PROFIT).first.values[:dif] || 0
  end

  def self.employee_balance(time_period_human, employee_public_id)
    now = Time.now.utc
    time_period =
      case time_period_human
      when "today"
        beginning_of_day = Time.utc(now.year, now.month, now.day)
        beginning_of_day..now
      when "alltime"
        Time.at(0)..now
      else
        raise "Not implemented"
      end
    where(performed_at: time_period)
      .where(account_public_id: employee_public_id)
      .select(UNPROFIT).first.values[:dif] || 0
  end
end

# Table: transactions
# Columns:
#  id                | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  public_id         | uuid                        | NOT NULL DEFAULT gen_random_uuid()
#  account_public_id | uuid                        | NOT NULL
#  type              | transaction_type            | NOT NULL
#  performed_at      | timestamp without time zone | NOT NULL DEFAULT now()
#  debit             | integer                     | NOT NULL DEFAULT 0
#  credit            | integer                     | NOT NULL DEFAULT 0
# Indexes:
#  transactions_pkey          | PRIMARY KEY btree (id)
#  transactions_public_id_key | UNIQUE btree (public_id)
