# frozen_string_literal: true

class Task < Sequel::Model
  STATUSES = %w[open closed].freeze
end

# Table: tasks
# Columns:
#  id                | integer     | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  description       | text        | NOT NULL DEFAULT ''::text
#  status            | task_status | NOT NULL DEFAULT 'open'::task_status
#  account_public_id | uuid        | NOT NULL
# Indexes:
#  tasks_pkey | PRIMARY KEY btree (id)
